# Site settings
title: 自然呆
#email: mrfeihao.AT.gmail.com
description: > # this means to ignore newlines until "baseurl:"
    来一发说写就写的博客吧
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.crystalsnow.info" # the base hostname & protocol for your site
twitter_username: feihao88
github_username:  suxue

# Build settings
markdown: kramdown
