# Site settings
title: Hao's Blog
email: hao@fei.id.au
description: > # this means to ignore newlines until "baseurl:"
    来一发说写就写的博客吧
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hao.fei.id.au" # the base hostname & protocol for your site
twitter_username: feihao88
github_username:  suxue

# Build settings
markdown: kramdown

kramdown:
    input: GFM # github favoured markdown
